syntax = "proto3";

package wargapos.rolebased.v1;

import "google/protobuf/descriptor.proto";

option go_package = "wargapos/backend/gen/wargapos/rolebased/v1;rolebasedv1";

enum Role {
  ROLE_UNSPECIFIED = 0;
  ROLE_ROOT = 1;
  ROLE_ADMIN = 2;
  ROLE_ACCOUNTANT = 3;
  ROLE_WAREHOUSE_ADMIN = 4;
  ROLE_WAREHOUSE_MEMBER = 5;
}

message RequestPolicy {
  repeated Role roles = 1;
}

message MethodPolicy {
  repeated Role roles = 1;
}

extend google.protobuf.MethodOptions {
  MethodPolicy method_policy = 50001;
}

extend google.protobuf.MessageOptions {
  RequestPolicy request_policy = 50001;
}
