syntax = "proto3";

package wargapos.connector.v1;

import "buf/validate/validate.proto";

option go_package = "wargapos/backend/gen/wargapos/connector/v1;connectorv1";

service ConnectorService {
  rpc Print(PrintRequest) returns (PrintResponse);
  rpc GetStatus(GetStatusRequest) returns (GetStatusResponse);
  rpc ListPrinters(ListPrintersRequest) returns (ListPrintersResponse);
}

message PrintRequest {
  string printer_name = 1 [(buf.validate.field).string.min_len = 1];
  oneof data {
    string string_data = 2;
    bytes bytes_data = 3;
  }
}

message ListPrintersResponse {
  repeated string names = 1;
}

message ListPrintersRequest {}

message PrintResponse {}

message GetStatusRequest {}

message GetStatusResponse {
  bool connected = 1;
  string printer_address = 2;
}
