// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"wargapos/backend/internal/config"
	"wargapos/backend/internal/service/connector_service"
)

// Injectors from wire.go:

func InitializeApp(cfg *config.Config) *App {
	connectorConfig := config.ProvideConnectorConfig(cfg)
	connectorService := connector_service.NewConnectorService(connectorConfig)
	app := NewApp(connectorConfig, connectorService)
	return app
}
