// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"wargapos/backend/internal/config"
	"wargapos/backend/internal/db"
	"wargapos/backend/internal/service/auth_service"
	"wargapos/backend/internal/service/product_service"
	"wargapos/backend/internal/service/transaction_service"
	"wargapos/backend/internal/service/user_service"
)

// Injectors from wire.go:

func InitializeApp(cfg *config.Config) (*App, error) {
	gormDB := db.NewDB(cfg)
	authConfig := config.ProvideAuthConfig(cfg)
	authService := auth_service.NewAuthService(gormDB, authConfig)
	userService := user_service.NewUserService(gormDB)
	productService := product_service.NewProductService(gormDB)
	transactionService := transaction_service.NewTransactionService(gormDB)
	app := NewApp(authService, userService, productService, transactionService)
	return app, nil
}
