// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"wargapos/backend/internal/config"
	"wargapos/backend/internal/db"
	"wargapos/backend/internal/service/auth_service"
	"wargapos/backend/internal/service/device_service"
	"wargapos/backend/internal/service/notification_service"
	"wargapos/backend/internal/service/product_service"
	"wargapos/backend/internal/service/settings_service"
	"wargapos/backend/internal/service/stock_service"
	"wargapos/backend/internal/service/table_service"
	"wargapos/backend/internal/service/transaction_service"
	"wargapos/backend/internal/service/user_service"
)

// Injectors from wire.go:

func InitializeApp(cfg *config.Config) (App, error) {
	gormDB := db.NewDB(cfg)
	midtransConfig := config.ProvideMidtransConfig(cfg)
	authConfig := config.ProvideAuthConfig(cfg)
	authService := auth_service.NewAuthService(gormDB, authConfig)
	userService := user_service.NewUserService(gormDB)
	productService := product_service.NewProductService(gormDB)
	transactionService := transaction_service.NewTransactionService(gormDB, midtransConfig)
	tableService := table_service.NewTableService(gormDB)
	settingsService := settings_service.NewSettingsService(gormDB, midtransConfig)
	stockService := stock_service.NewStockService(gormDB)
	deviceService := device_service.NewDeviceService()
	notificationService := notification_service.NewNotificationService(gormDB)
	webRunnerFunc := NewWebRunnerFunc(gormDB, cfg, midtransConfig, authConfig, authService, userService, productService, transactionService, tableService, settingsService, stockService, deviceService, notificationService)
	runner := transaction_service.NewTransactionRunner()
	partitionRunner := NewPartitionRunner(gormDB)
	partitionRunnerFunc := NewPartitionRunnerFunc(partitionRunner)
	app := NewApp(webRunnerFunc, runner, partitionRunnerFunc)
	return app, nil
}
