// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"wargapos/backend/internal/config"
	"wargapos/backend/internal/database"
	"wargapos/backend/internal/service/auth_service"
	"wargapos/backend/internal/service/backup_service"
	"wargapos/backend/internal/service/device_service"
	"wargapos/backend/internal/service/event_service"
	"wargapos/backend/internal/service/ingredient_service"
	"wargapos/backend/internal/service/marketplace_service"
	"wargapos/backend/internal/service/notification_service"
	"wargapos/backend/internal/service/product_service"
	"wargapos/backend/internal/service/settings_service"
	"wargapos/backend/internal/service/stock_service"
	"wargapos/backend/internal/service/table_service"
	"wargapos/backend/internal/service/transaction_service"
	"wargapos/backend/internal/service/user_service"
)

// Injectors from wire.go:

func InitializeApp(cfg *config.Config) (App, error) {
	db := database.NewDB(cfg)
	midtransConfig := config.ProvideMidtransConfig(cfg)
	authConfig := config.ProvideAuthConfig(cfg)
	authService := auth_service.NewAuthService(db, authConfig)
	userService := user_service.NewUserService(db)
	eventService := event_service.NewEventService()
	productService := product_service.NewProductService(db)
	transactionService := transaction_service.NewTransactionService(db, midtransConfig)
	tableService := table_service.NewTableService(db)
	settingsService := settings_service.NewSettingsService(db, midtransConfig)
	eventServiceClient := NewEventServiceClient(cfg)
	stockService := stock_service.NewStockService(db, eventServiceClient)
	defaultServiceClientOption := NewDefaultServiceClientOption()
	stockServiceClient := NewStockServiceClient(cfg, defaultServiceClientOption)
	ingredientService := ingredient_service.NewIngredientService(db, stockServiceClient)
	marketplaceService := marketplace_service.NewMarketplaceService(cfg, db, stockServiceClient)
	deviceService := device_service.NewDeviceService()
	notificationService := notification_service.NewNotificationService(db)
	backupService := backup_service.NewBackupService(db, cfg, authConfig)
	webRunnerFunc := NewWebRunnerFunc(db, cfg, midtransConfig, authConfig, authService, userService, eventService, productService, transactionService, tableService, settingsService, stockService, ingredientService, marketplaceService, deviceService, notificationService, backupService)
	runner := transaction_service.NewTransactionRunner()
	partitionRunner := NewPartitionRunner(db)
	partitionRunnerFunc := NewPartitionRunnerFunc(partitionRunner)
	app := NewApp(webRunnerFunc, runner, partitionRunnerFunc, eventService, marketplaceService)
	return app, nil
}
