syntax = "proto3";

package wargapos.stock.v1;

import "buf/validate/validate.proto";
import "wargapos/stock/v1/stock.proto";
import "wargapos/rolebased/v1/role.proto";

option go_package = "wargapos/backend/gen/wargapos/stock/v1;stockv1";

message ListStockLogSkuRequest {
  option (wargapos.rolebased.v1.request_policy) = { roles: [ROLE_ROOT, ROLE_ADMIN, ROLE_WAREHOUSE_ADMIN, ROLE_WAREHOUSE_MEMBER] };
  uint32 sku_id = 1 [(buf.validate.field).uint32.gt = 0];
  int32 page = 2;
  int32 page_size = 3;
}
message ListStockLogSkuResponse { repeated StockLog logs = 1; int32 total = 2; }
