syntax = "proto3";

package wargapos.stock.v1;

import "buf/validate/validate.proto";
import "google/protobuf/timestamp.proto";

option go_package = "wargapos/backend/gen/wargapos/stock/v1;stockv1";

enum LogType {
  LOG_TYPE_UNSPECIFIED = 0;
  LOG_TYPE_STOCK_CANCEL = 1;
  LOG_TYPE_STOCK_IN = 2;
  LOG_TYPE_STOCK_OUT = 3;
  LOG_TYPE_ADJUSTMENT = 4;
  LOG_TYPE_ORDER = 5;
}

message CostVersion {
  uint64 id = 1;
  uint32 sku_id = 2;
  uint64 transaction_id = 3;
  google.protobuf.Timestamp created_at = 4;
  google.protobuf.Timestamp updated_at = 5;

  double unit_cost = 6;
  int32 stock_initiate = 7;
  int32 left_stock = 8;
}

message StockLog {
  uint64 id = 1;
  uint32 sku_id = 2;
  uint64 transaction_id = 4;
  uint32 actor_id = 5;
  google.protobuf.Timestamp created_at = 8;
  LogType log_type = 9;
  int32 change = 10;
}

message ListCostSkuRequest {
  uint32 sku_id = 1 [(buf.validate.field).uint32.gt = 0];
}
message ListCostSkuResponse {
  repeated CostVersion costs = 1;
}
