syntax = "proto3";

package wargapos.stock.v1;

import "buf/validate/validate.proto";
import "google/protobuf/timestamp.proto";

option go_package = "wargapos/backend/gen/wargapos/stock/v1;stockv1";

message PriceVersion {
  uint64 id = 1;
  uint32 sku_id = 2;
  uint32 transaction_id = 3;
  google.protobuf.Timestamp created_at = 4;
  google.protobuf.Timestamp updated_at = 5;

  uint64 price = 6;
  uint32 stock_initiate = 7;
  uint32 left_stock = 8;
}

message Stock {
  uint64 id = 1;
  uint32 sku_id = 2;
  uint32 transaction_id = 3;
  google.protobuf.Timestamp created_at = 4;
  google.protobuf.Timestamp updated_at = 5;

  uint32 stock_initiate = 6;
  uint32 left_stock = 7;
}

message StockLog {
  uint64 id = 1;
  uint32 sku_id = 2;
  uint32 warehouse_id = 3;
  uint32 transaction_id = 4;
  uint32 change_by_id = 5;
  uint64 price_version_id = 6;
  uint64 stock_id = 7;
  google.protobuf.Timestamp created_at = 8;
}

message ListPriceSkuRequest {
  uint32 sku_id = 1 [(buf.validate.field).uint32.gt = 0];
}
message ListPriceSkuResponse {
  repeated PriceVersion prices = 1;
}

message ListStockSkuRequest {
  uint32 sku_id = 1 [(buf.validate.field).uint32.gt = 0];
}
message ListStockSkuResponse {
  repeated Stock stocks = 1;
}
