syntax = "proto3";

package wargapos.stock.v1;

import "buf/validate/validate.proto";
import "google/protobuf/timestamp.proto";
import "wargapos/rolebased/v1/role.proto";
import "wargapos/stock/v1/placement.proto";

option go_package = "wargapos/backend/gen/wargapos/stock/v1;stockv1";

enum TransactionType {
  TRANSACTION_TYPE_UNSPECIFIED = 0;
  TRANSACTION_TYPE_STOCK_IN = 1;
  TRANSACTION_TYPE_STOCK_OUT = 2;
  TRANSACTION_TYPE_PLACE_ADJUSTMENT = 3;
  TRANSACTION_TYPE_PROBLEM = 4;
  TRANSACTION_TYPE_ORDER = 5;
}

enum PlacementStatus {
  PLACEMENT_STATUS_UNSPECIFIED = 0;
  PLACEMENT_STATUS_REVIEW = 1;
  PLACEMENT_STATUS_SET = 2;
}

message Transaction {
  uint64 id = 1;
  TransactionType transaction_type = 2;
  PlacementStatus placement_status = 10;
  google.protobuf.Timestamp created_at = 3;
  string note = 4;
  bool cancelled = 5;
  repeated TransactionItem items = 6;
  double total = 7;
  int32 product_count = 8;
  int32 pieces_count = 9;
  string receipt = 11;
  string receipt_file = 12;
}

message TransactionItem {
  uint32 sku_id = 1 [(buf.validate.field).uint32.gt = 0];
  int32 quantity = 2 [(buf.validate.field).int32.not_in = 0];
  double total = 3 [(buf.validate.field).double.gt = 0];
}

message StockInPlacementPayload {
  uint32 rack_id = 1 [(buf.validate.field).uint32 = {gt: 0}];
  uint32 sku_id = 2 [(buf.validate.field).uint32 = {gt: 0}];
  int32 count = 3 [(buf.validate.field).int32 = {
    gt: 0 // stock-in must be positive
  }];
}

message StockInCreate { // TRANSACTION_TYPE_STOCK_IN
  repeated StockInPlacementPayload placement = 1 [(buf.validate.field).repeated = {
    min_items: 1
    max_items: 100
  }];
  repeated TransactionItem items = 2 [(buf.validate.field).repeated.min_items = 1];
}

message MovePayload {
  uint32 from_rack_id = 1 [(buf.validate.field).uint32 = {
    gt: 0 // must be valid source rack
  }];

  uint32 to_rack_id = 2 [(buf.validate.field).uint32 = {
    gt: 0 // must be valid destination rack
  }];

  int32 change = 3 [(buf.validate.field).int32 = {
    gt: 0 // movement amount must be positive
  }];

  uint32 sku_id = 4 [(buf.validate.field).uint32.gt = 0];
}

message MoveCreate {
  repeated MovePayload move = 1 [(buf.validate.field).repeated = {
    min_items: 1
    max_items: 100
  }];
}

message ProblemPayload {
  uint32 rack_id = 1 [(buf.validate.field).uint32 = {
    gt: 0 // must be a valid rack id
  }];

  int32 count = 2 [(buf.validate.field).int32 = {
    not_in: [0] /* cannot be zero */
  }];

  PlacementType type = 3 [(buf.validate.field).enum = {
    defined_only: true
  }];

  string reason = 4 [(buf.validate.field).string = {
    min_len: 3
    max_len: 255
    pattern: ".*\\S.*"
  }];

  uint32 sku_id = 5 [(buf.validate.field).uint32.gt = 0];
}

message ProblemCreate {
  repeated ProblemPayload problem = 1 [(buf.validate.field).repeated = {
    min_items: 1
    max_items: 100
  }];
}

message OrderCreate {
  string receipt = 1 [(buf.validate.field).string = {
    min_len: 1
    max_len: 100
  }];

  string receipt_file = 2 [(buf.validate.field).string = {
    min_len: 1
    pattern: "^(https?://.+|/.*|\\.?\\.?/.*)$"
  }];

  repeated TransactionItem items = 3 [(buf.validate.field).repeated.min_items = 1];
}

message CreateTransactionRequest {
  option (wargapos.rolebased.v1.request_policy) = {
    roles: [
      ROLE_ROOT,
      ROLE_ADMIN,
      ROLE_WAREHOUSE_ADMIN
    ]
  };

  oneof kind {
    StockInCreate stock_in = 1;
    MoveCreate move = 2;
    ProblemCreate problem = 3;
    OrderCreate order = 4;
  }

  string note = 5;
}

message CreateTransactionResponse {
  Transaction transaction = 1;
}

message CancelTransactionRequest {
  option (wargapos.rolebased.v1.request_policy) = {
    roles: [
      ROLE_ROOT,
      ROLE_ADMIN,
      ROLE_WAREHOUSE_ADMIN
    ]
  };
  uint64 transaction_id = 1 [(buf.validate.field).uint64.gt = 0];
  string reason = 2;
}
message CancelTransactionResponse {}

message ListTransactionRequest {
  option (wargapos.rolebased.v1.request_policy) = {
    roles: [
      ROLE_ROOT,
      ROLE_ADMIN,
      ROLE_WAREHOUSE_ADMIN,
      ROLE_WAREHOUSE_MEMBER,
      ROLE_CASHIER
    ]
  };
  int32 page = 1;
  int32 page_size = 2;
  TransactionType transaction_type = 3;
  bool cancelled = 4;
  string date_from = 5;
  string date_to = 6;
}
message ListTransactionResponse {
  repeated Transaction transactions = 1;
  int32 total = 2;
}

message DetailTransactionRequest {
  option (wargapos.rolebased.v1.request_policy) = {
    roles: [
      ROLE_ROOT,
      ROLE_ADMIN,
      ROLE_WAREHOUSE_ADMIN,
      ROLE_WAREHOUSE_MEMBER,
      ROLE_CASHIER
    ]
  };
  uint64 id = 1 [(buf.validate.field).uint64.gt = 0];
}
message DetailTransactionResponse {
  Transaction transaction = 1;
}
