syntax = "proto3";

package wargapos.marketplace.v1;

option go_package = "wargapos/backend/gen/wargapos/marketplace/v1;marketplacev1";

import "google/protobuf/timestamp.proto";

message MarketplaceCustomer {
  uint64 id = 1;
  string name = 2;
  string phone_number = 3;
  google.protobuf.Timestamp created_at = 4;
  google.protobuf.Timestamp updated_at = 5;
}

message CustomerAddress {
  uint64 id = 1;
  uint64 customer_id = 2;
  string label = 3;
  string address = 4;
  string city = 5;
  string province = 6;
  string postal_code = 7;
  google.protobuf.Timestamp created_at = 8;
  google.protobuf.Timestamp updated_at = 9;
}
