syntax = "proto3";

package wargapos.marketplace.v1;

import "google/protobuf/timestamp.proto";

option go_package = "wargapos/backend/gen/wargapos/marketplace/v1;marketplacev1";

message WarehouseStock {
  uint32 warehouse_id = 1;
  uint32 sku_id = 2;
  int32 left_stock = 3;
  double stock_valuation = 4;
}

message MarketplaceProduct {
  uint64 id = 1;
  string name = 2;
  string description = 3;
  int64 price_cents = 4;
  string image_url = 5;
  bool is_active = 6;
  int32 left_stock = 9;
  double stock_valuation = 11;
  repeated WarehouseStock warehouse_stock = 10;
  google.protobuf.Timestamp created_at = 7;
  google.protobuf.Timestamp updated_at = 8;
}
