syntax = "proto3";

package wargapos.backup.v1;

// import "buf/validate/validate.proto";
import "wargapos/rolebased/v1/role.proto";

option go_package = "wargapos/backend/gen/wargapos/backup/v1;backupv1";

service BackupService {
  rpc RunBackup(RunBackupRequest) returns (stream RunBackupResponse);
  rpc ListBackup(ListBackupRequest) returns (ListBackupResponse);
  rpc DeleteBackup(DeleteBackupRequest) returns (DeleteBackupResponse);
  rpc RestoreBackup(RestoreBackupRequest) returns (stream RestoreBackupResponse);
}

message RunBackupRequest {
  option (wargapos.rolebased.v1.request_policy) = { roles: [ROLE_ROOT, ROLE_ADMIN] };
}
message RunBackupResponse {
  oneof data {
    string filepath = 1;
    string msg = 2;
  }
}

message ListBackupRequest {
  option (wargapos.rolebased.v1.request_policy) = { roles: [ROLE_ROOT, ROLE_ADMIN] };
}
message ListBackupResponse {
  repeated string fnames = 1;
}

message DeleteBackupRequest {
  option (wargapos.rolebased.v1.request_policy) = { roles: [ROLE_ROOT, ROLE_ADMIN] };
  string fname = 1;
}
message DeleteBackupResponse {}

message RestoreBackupRequest {
  option (wargapos.rolebased.v1.request_policy) = { roles: [ROLE_ROOT, ROLE_ADMIN] };
  string fname = 1;
}
message RestoreBackupResponse {
  string msg = 1;
}
