syntax = "proto3";

package wargapos.event.v1;

import "buf/validate/validate.proto";
// import "google/protobuf/timestamp.proto";
import "wargapos/stock/v1/event.proto";

option go_package = "wargapos/backend/gen/wargapos/event/v1;eventv1";

service EventService {
  rpc Send(SendRequest) returns (SendResponse);
  rpc Pull(PullRequest) returns (stream PullResponse);
}

service PushService {
  rpc Push(PushRequest) returns (PushResponse);
}

message Ping {}

message Event {
  oneof event {
    Ping ping = 1;
    wargapos.stock.v1.StockEvent stock_event = 2;
  }
}

message SendRequest {
  string push_id = 1;
  Event evt = 2;
}
message SendResponse {}

message PullResponse {
  Event evt = 2;
}
message PullRequest {
  string subscribe_id = 1 [(buf.validate.field).string = {
    min_len: 1
    max_len: 300
  }];
}

message PushRequest {
  Event evt = 2;
}

message PushResponse {}
